import { Router, type IRouter } from "express";
import healthRouter from "./health";
import jobsRouter from "./jobs";
import bookingsRouter from "./bookings";
import projectsRouter from "./projects";
import electricalProjectsRouter from "./electricalProjects";
import gasfittingProjectsRouter from "./gasfittingProjects";
import plumbingProjectsRouter from "./plumbingProjects";
import hvacProjectsRouter from "./hvacProjects";
import plowingProjectsRouter from "./plowingProjects";
import teamMembersRouter from "./teamMembers";
import eyespyrRouter from "./eyespyr";
import vaultPdfRouter from "./vaultPdf";
import vaultEmailRouter from "./vaultEmail";
import safetyCreditsRouter from "./safetyCredits";
import hardscapingProjectsRouter from "./hardscapingProjects";
import complianceDocsRouter from "./complianceDocs";
import vanStockRouter from "./vanStock";
import permitSpyRouter from "./permitSpy";
import plowDriversRouter from "./plowDrivers";
import backhaulTrucksRouter from "./backhaulTrucks";
import errandsRouter from "./errands";
import fabricationProjectsRouter from "./fabricationProjects";
import contractorsRouter from "./contractors";
import snapPostsRouter from "./snapPosts";
import cityPagesRouter from "./cityPages";
import whatsappWebhookRouter from "./whatsappWebhook";
import performanceReportRouter from "./performanceReport";
import performanceReportPdfRouter from "./performanceReportPdf";
import cityPagePublicRouter from "./cityPagePublic";
import contractorProfileRouter from "./contractorProfile";
import networkDirectoryRouter from "./networkDirectory";
import contentFeedRouter from "./contentFeed";
import seoScorecardRouter from "./seoScorecard";
import iamaiRouter from "./iamai";

const router: IRouter = Router();

router.use(healthRouter);
router.use(jobsRouter);
router.use(bookingsRouter);
router.use(projectsRouter);
router.use(electricalProjectsRouter);
router.use(gasfittingProjectsRouter);
router.use(plumbingProjectsRouter);
router.use(hvacProjectsRouter);
router.use(plowingProjectsRouter);
router.use(teamMembersRouter);
router.use(eyespyrRouter);
router.use(vaultPdfRouter);
router.use(vaultEmailRouter);
router.use("/safety-credits", safetyCreditsRouter);
router.use(hardscapingProjectsRouter);
router.use(complianceDocsRouter);
router.use(vanStockRouter);
router.use(permitSpyRouter);
router.use(plowDriversRouter);
router.use(backhaulTrucksRouter);
router.use(errandsRouter);
router.use(fabricationProjectsRouter);
router.use(contractorsRouter);
router.use(snapPostsRouter);
router.use(cityPagesRouter);
router.use(whatsappWebhookRouter);
router.use(performanceReportRouter);
router.use(performanceReportPdfRouter);
router.use(cityPagePublicRouter);
router.use(contractorProfileRouter);
router.use(networkDirectoryRouter);
router.use(contentFeedRouter);
router.use(seoScorecardRouter);
router.use(iamaiRouter);

export default router;
